<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260211193005 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Создание таблиц country_taxes, coupons, products';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
CREATE TABLE country_taxes (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
    code VARCHAR(255) NOT NULL, 
    amount INT NOT NULL, 
    PRIMARY KEY (id))
SQL
);
        $this->addSql(<<<'SQL'
CREATE UNIQUE INDEX country_taxes_uni_idx_code ON country_taxes (code)
SQL
);
        $this->addSql(<<<'SQL'
CREATE TABLE coupons (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
    code VARCHAR(255) NOT NULL, 
    amount INT NOT NULL, 
    type VARCHAR(255) NOT NULL, 
    PRIMARY KEY (id))
SQL
);
        $this->addSql(<<<'SQL'
CREATE UNIQUE INDEX coupons_uni_idx_code ON coupons (code)
SQL
);
        $this->addSql(<<<'SQL'
CREATE TABLE products (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
    title VARCHAR(255) NOT NULL, 
    price INT NOT NULL, 
    PRIMARY KEY (id))
SQL
);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE country_taxes');
        $this->addSql('DROP TABLE coupons');
        $this->addSql('DROP TABLE products');
    }
}
